clear;
close all;
symulacja_obiektu15_p4(0,0,0,0, ...
                        0,0,0,0, ...
                        0,0,0,0, ...
                        0,0,0,0, ...
                        0,0,0,0, ...
                        0,0,0,0, ...
                        0,0,0,0);
SIM_LENGHT = 500;
Y = zeros(SIM_LENGHT,3);
U = zeros(SIM_LENGHT,4);
STEP_MOMENT = 30;
for k=STEP_MOMENT:SIM_LENGHT
    Y(k) = symulacja_obiektu15_p4( ...
        U(k-1,1), U(k-2,1), U(k-3,1), U(k-4,1), ...
        U(k-1,2), U(k-2,2), U(k-3,2), U(k-4,2), ...
        U(k-1,3), U(k-2,3), U(k-3,3), U(k-4,3), ...
        U(k-1,4), U(k-2,4), U(k-3,4), U(k-4,4), ...
        Y(k-1,1), Y(k-2,1), Y(k-3,1), Y(k-4,1), ...
        Y(k-1,2), Y(k-2,2), Y(k-3,2), Y(k-4,2), ...
        Y(k-1,3), Y(k-2,3), Y(k-3,3), Y(k-4,3));
end
figure(1)
fig = stairs(Y(:,1));
writematrix([fig.XData; fig.YData]', 'txts/ad1_y1.txt', "Delimiter","tab");
figure(2)
fig = stairs(Y(:,2));
writematrix([fig.XData; fig.YData]', 'txts/ad1_y2.txt', "Delimiter","tab");
figure(3)
fig = stairs(Y(:,3));
writematrix([fig.XData; fig.YData]', 'txts/ad1_y3.txt', "Delimiter","tab");